centos_6:
    spec: debian/shinken.spec
    deps_pip:
        - Sphinx==1.2.3
    deps:
        - gcc
        - make
centos_7:
    spec: debian/shinken.spec
    deps_pip:
        - sphinx
debian_8:
    debian: debian
ubuntu_10.04:
    debian: debian.lucid
ubuntu_12.04:
    debian: debian
ubuntu_14.04:
    debian: debian
