language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r shinken/dependencies || pip install -r requirements.txt
  - ./bin/preparedev

# command to run tests
script: cd test && nosetests -x -s -v --process-restartworker --processes=1 --process-timeout=999999999

git:
  depth: 100

